name: Cloud Provider Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    environment: cloud-VMs

    strategy:
      matrix:
        # Self-hosted runner setup for cloud provider testing.
        # Assuming Ubuntu environment on AWS EC2, GCP Compute Engine, or Azure VM.
        #
        # Base system setup:
        # sudo apt update
        # sudo snap install go --classic
        # sudo apt install -y python3 python3-pip python3-venv
        #
        # AWS EC2 setup:
        # sudo snap install aws-cli --classic
        # Ensure EC2 instance has IAM role attached for AWS credential access
        #
        # GCP Compute Engine setup:
        # Ensure VM has service account attached with appropriate permissions
        # GCP credentials are automatically available via metadata service
        #
        # Azure VM setup:
        # curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        # az vm identity assign --name $vm_name --resource-group $resource_group
        # Ensure VM has managed identity enabled for Azure credential access
        #
        # Environment Variables for testing:
        # S2IAM_TEST_ASSUME_ROLE - Set to a role ARN/identifier to test role assumption (AWS/GCP only)
        # S2IAM_TEST_CLOUD_PROVIDER - Set to indicate cloud tests should run (aws/gcp/azure)
        # S2IAM_DEBUGGING - Set to true for verbose test output
        #
        # Both Go and Python testing are fully automated via GitHub Actions
        # Go: Runs integration tests with coverage reporting (go coverage format)
        # Python: Uses automated validation framework with coverage reporting (XML format)
        # Coverage from all environments (no CSP, AWS, Azure, GCP) is uploaded to Codecov
        #
        include:
          - name: aws-positive
            username: ubuntu
            hostname: ec2-18-206-180-126.compute-1.amazonaws.com
            secret: AWS_POSITIVE_KEY
            env_vars: "S2IAM_TEST_ASSUME_ROLE=arn:aws:iam::503396375767:role/NoPermissionsRole"
          - name: aws-negative
            username: ubuntu
            hostname: ec2-35-173-183-101.compute-1.amazonaws.com
            secret: AWS_POSITIVE_KEY
            env_vars: "S2IAM_TEST_CLOUD_PROVIDER_NO_ROLE=aws"
          - name: azure-positive
            username: azureuser
            hostname: 52.186.98.155
            secret: AZURE_POSITIVE_KEY
            env_vars: "S2IAM_TEST_CLOUD_PROVIDER=azure"
          - name: azure-negateive
            username: azureuser
            hostname: 74.235.105.73
            secret: AZURE_NEGATIVE_KEY
            env_vars: "S2IAM_TEST_CLOUD_PROVIDER_NO_ROLE=azure"
          - name: gcp-positive
            username: dsharnoff
            hostname: 34.145.164.5
            secret: GCP_POSITIVE_KEY
            env_vars: "S2IAM_TEST_CLOUD_PROVIDER=gcp"
            # assume role permissions are not yet working
            # env_vars: "S2IAM_TEST_ASSUME_ROLE=nopermissionsrole@gcp-virginia-hd1.iam.gserviceaccount.com"
          - name: gcp-negative
            username: dsharnoff
            hostname: 34.21.55.72
            secret: GCP_POSITIVE_KEY
            env_vars: "S2IAM_TEST_CLOUD_PROVIDER_NO_ROLE=gcp"
    
    env:
      TEST_USERNAME: ${{ matrix.username }}
      TEST_HOSTNAME: ${{ matrix.hostname }}
      SSH_KEY_SECRET: ${{ matrix.secret }}
      UNIQUE_DIR: test-${{ github.run_id }}-${{ github.run_attempt }}-${{ matrix.name }}
      EXTRA_ENV: ${{ matrix.env_vars }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets[env.SSH_KEY_SECRET] }}" > ~/.ssh/key
        chmod 600 ~/.ssh/key
        ssh-keyscan -H ${{ env.TEST_HOSTNAME }} >> ~/.ssh/known_hosts
        ssh -i ~/.ssh/key -o StrictHostKeyChecking=no -o ConnectTimeout=10 \
          ${{ env.TEST_USERNAME }}@${{ env.TEST_HOSTNAME }} "mkdir -p tests && echo 'SSH connection successful'"
    
    - name: Copy repository to remote system
      run: |
        tar -czf - --exclude=.git .  | ssh -i ~/.ssh/key -o StrictHostKeyChecking=no \
          "${{ env.TEST_USERNAME }}@${{ env.TEST_HOSTNAME }}" \
          "mkdir -p tests/${{ env.UNIQUE_DIR }} && cd tests/${{ env.UNIQUE_DIR }} && tar xzf -"
    
    - name: Run Go tests with coverage and verification
      run: |
        ssh -i ~/.ssh/key -o StrictHostKeyChecking=no ${{ env.TEST_USERNAME }}@${{ env.TEST_HOSTNAME }} << 'EOF' 2>&1 | tee test_output.log
          set -ex
          cd tests/${{ env.UNIQUE_DIR }}/go
          
          env ${{ env.EXTRA_ENV }} go test -v --failfast ./... 
          
          env ${{ env.EXTRA_ENV }} go test -covermode=atomic -coverprofile=coverage.out -coverpkg=github.com/singlestore-labs/singlestore-auth-iam/... ./...

          ls -la coverage.out
        EOF

    - name: Run Python tests with coverage
      run: |
        ssh -i ~/.ssh/key -o StrictHostKeyChecking=no ${{ env.TEST_USERNAME }}@${{ env.TEST_HOSTNAME }} << 'EOF' 2>&1 | tee python_test_output.log
          set -ex
          cd tests/${{ env.UNIQUE_DIR }}/python
          
          # Install Python 3 if not available
          if ! command -v python3 &> /dev/null; then
            sudo apt update
            sudo apt install -y python3 python3-pip python3-venv
          fi
          
          # Run Python tests with coverage using our automated validation framework
          env ${{ env.EXTRA_ENV }} S2IAM_DEBUGGING=true ./tests/run_cloud_validation.sh --coverage
          
          # Verify coverage file was generated
          ls -la coverage.xml
        EOF
    
    - name: Verify test results
      run: |
        echo "=== Verifying Go test results ==="
        echo "Checking for TestWithDebugging..."
        grep --silent -- "--- PASS: TestWithDebugging" test_output.log
        echo "Checking for PASS..."
        grep --silent -- "^PASS" test_output.log
        echo "Showing ok lines..."
        grep "^ok" test_output.log
        echo "Checking cmd pattern..."
        grep --silent "^ok  	github.com/singlestore-labs/singlestore-auth-iam/go/cmd	" test_output.log
        echo "Checking s2iam pattern..."
        grep --silent "^ok  	github.com/singlestore-labs/singlestore-auth-iam/go/cmd/s2iam	" test_output.log
        echo "Checking s2iam_test_server pattern..."
        grep --silent "^ok  	github.com/singlestore-labs/singlestore-auth-iam/go/cmd/s2iam_test_server	" test_output.log
        echo "Checking s2iam package pattern..."
        grep --silent "^ok  	github.com/singlestore-labs/singlestore-auth-iam/go/s2iam	" test_output.log
        echo "Go tests passed successfully!"
        
        echo "=== Verifying Python test results ==="
        echo "Checking for Python test completion..."
        grep --silent "Test run completed successfully!" python_test_output.log
        echo "Python tests passed successfully!"
        
        echo "All tests passed successfully!"
    
    - name: Download Go coverage file
      run: |
        # Verify coverage file exists on remote
        ssh -i ~/.ssh/key -o StrictHostKeyChecking=no \
          ${{ env.TEST_USERNAME }}@${{ env.TEST_HOSTNAME }} \
          "ls -la tests/${{ env.UNIQUE_DIR }}/go/coverage.out"
        
        # Download coverage file from remote
        scp -i ~/.ssh/key -o StrictHostKeyChecking=no \
          ${{ env.TEST_USERNAME }}@${{ env.TEST_HOSTNAME }}:tests/${{ env.UNIQUE_DIR }}/go/coverage.out ./go-coverage.out
          
        # Verify local coverage file
        echo "Local Go coverage file: $(ls -la go-coverage.out)"

    - name: Download Python coverage file
      run: |
        # Verify Python coverage file exists on remote
        ssh -i ~/.ssh/key -o StrictHostKeyChecking=no \
          ${{ env.TEST_USERNAME }}@${{ env.TEST_HOSTNAME }} \
          "ls -la tests/${{ env.UNIQUE_DIR }}/python/coverage.xml"
        
        # Download Python coverage file from remote
        scp -i ~/.ssh/key -o StrictHostKeyChecking=no \
          ${{ env.TEST_USERNAME }}@${{ env.TEST_HOSTNAME }}:tests/${{ env.UNIQUE_DIR }}/python/coverage.xml ./python-coverage.xml
          
        # Verify local Python coverage file
        echo "Local Python coverage file: $(ls -la python-coverage.xml)"

    - name: Display Go coverage
      run: |
        echo "=== Go Coverage ==="
        echo "Original coverage file paths:"
        (grep azure go-coverage.out | head) || echo no azure in go coverage
        head -2 go-coverage.out
        echo ""
        echo "=== Python Coverage ==="
        echo "Python coverage summary:"
        head -10 python-coverage.xml

    - name: Upload Go coverage to Codecov
      uses: codecov/codecov-action@v5.4.3
      with:
        fail_ci_if_error: true
        name: ${{ matrix.name }}-go-coverage
        file: ./go-coverage.out
        flags: go,${{ matrix.name }}
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    - name: Upload Python coverage to Codecov
      uses: codecov/codecov-action@v5.4.3
      with:
        fail_ci_if_error: true
        name: ${{ matrix.name }}-python-coverage
        file: ./python-coverage.xml
        flags: python,${{ matrix.name }}
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    - name: Clean up remote directory
      if: always()
      run: |
        ssh -i ~/.ssh/key -o StrictHostKeyChecking=no ${{ env.TEST_USERNAME }}@${{ env.TEST_HOSTNAME }} "rm -rf tests/${{ env.UNIQUE_DIR }}"

    - name: Cleanup SSH key
      if: always()
      run: |
        rm -f ~/.ssh/key
